/* problem1: generated by ppy, C++17 */
#include <cinttypes>
#include <cstdint>
#include <cstdio>

namespace problem1 {
std::int64_t parking_fee(std::int64_t minutes);
} // namespace problem1


int main() {
    std::int64_t number_of_cars;
    std::int64_t parking_time;
    std::int64_t fee;

    std::printf("===Parking Fee Calculator===\n");
    std::printf("Number of cars: ");
    std::fflush(stdout);
    if (std::scanf("%" SCNd64, &number_of_cars) != 1) { return 1; }
    std::int64_t total_fee = 0;
    std::int64_t free_cars = 0;
    std::int64_t car = 1;
    while (car <= number_of_cars) {
        std::printf("Car %" PRId64 " parking time (minutes): ", car);
        std::fflush(stdout);
        if (std::scanf("%" SCNd64, &parking_time) != 1) { return 1; }
        fee = problem1::parking_fee(parking_time);
        std::printf("Car %" PRId64 " fee: %" PRId64 " won\n", car, fee);
        total_fee += fee;
        if (fee == 0) {
            free_cars += 1;
        }
        car += 1;
    }
    std::printf("Total fee: %" PRId64 " won, Free cars: %" PRId64 "\n", total_fee, free_cars);
    return 0;
}

namespace problem1 {
std::int64_t parking_fee(std::int64_t minutes) {
    if (minutes <= 30) return 0;
    std::int64_t chargeable_minutes = minutes - 30;
    std::int64_t r = static_cast<std::int64_t>(chargeable_minutes + 9) % 10;
    std::int64_t q = static_cast<std::int64_t>(chargeable_minutes + 9) / 10;
    std::int64_t units = (r != 0 && (static_cast<std::int64_t>(chargeable_minutes + 9) < 0) != (10 < 0)) ? q - 1 : q;
    std::int64_t fee = units * 500;
    if (fee > 5000) {
        fee = 5000;
    }
    return fee;
}

} // namespace problem1
