/* problem1: generated by ppy, C11 */
#include <limits.h>
#include <stdio.h>

_Static_assert(INT_MAX == 2147483647 && INT_MIN == (-2147483647 - 1),
               "this program requires 32-bit int");

static int parking_fee(int minutes) {
    if (minutes <= 30) return 0;
    int chargeable_minutes = minutes - 30;
    int units = (chargeable_minutes + 9) / 10;
    int fee = units * 500;
    if (fee > 5000) {
        fee = 5000;
    }
    return fee;
}

int main(void) {
    printf("===Parking Fee Calculator===\n");
    printf("Number of cars: ");
    fflush(stdout);
    int number_of_cars;
    if (scanf("%d", &number_of_cars) != 1) {
        return 1;
    }
    int total_fee = 0;
    int free_cars = 0;
    int car = 1;
    while (car <= number_of_cars) {
        printf("Car %d parking time (minutes): ", car);
        fflush(stdout);
        int parking_time;
        if (scanf("%d", &parking_time) != 1) {
            return 1;
        }
        int fee = parking_fee(parking_time);
        printf("Car %d fee: %d won\n", car, fee);
        total_fee += fee;
        if (fee == 0) {
            free_cars += 1;
        }
        car += 1;
    }
    printf("Total fee: %d won, Free cars: %d\n", total_fee, free_cars);
    return 0;
}
