/* problem2: generated by ppy, C++17 */
#include <climits>
#include <cstdio>

static_assert(INT_MAX == 2147483647 && INT_MIN == (-2147483647 - 1),
              "this program requires 32-bit int");

namespace problem2 {
int parking_fee(int minutes) {
    if (minutes <= 30) return 0;
    int chargeable_minutes = minutes - 30;
    int units = (chargeable_minutes + 9) / 10;
    int fee = units * 500;
    if (fee > 5000) {
        fee = 5000;
    }
    return fee;
}

int maximum_parking_time(int budget) {
    int minute = 0;
    int maximum_time = 0;
    while (minute <= 1440) {
        int fee = problem2::parking_fee(minute);
        if (fee <= budget) {
            maximum_time = minute;
        }
        minute += 1;
    }
    return maximum_time;
}

} // namespace problem2

int main() {
    std::printf("===Maximum Parking Time===\n");
    std::printf("Budget (won): ");
    std::fflush(stdout);
    int budget;
    if (std::scanf("%d", &budget) != 1) {
        return 1;
    }
    int maximum_time;
    maximum_time = problem2::maximum_parking_time(budget);
    std::printf("Maximum parking time: %d minutes\n", maximum_time);
    return 0;
}
