/* problem1: generated by ppy, C11 */
#include <inttypes.h>
#include <stdint.h>
#include <stdio.h>

static int64_t parking_fee(int64_t minutes);

int main(void) {
    int64_t number_of_cars;
    int64_t parking_time;
    int64_t fee;

    printf("===Parking Fee Calculator===\n");
    printf("Number of cars: ");
    fflush(stdout);
    if (scanf("%" SCNd64, &number_of_cars) != 1) { return 1; }
    int64_t total_fee = 0;
    int64_t free_cars = 0;
    int64_t car = 1;
    while (car <= number_of_cars) {
        printf("Car %" PRId64 " parking time (minutes): ", car);
        fflush(stdout);
        if (scanf("%" SCNd64, &parking_time) != 1) { return 1; }
        fee = parking_fee(parking_time);
        printf("Car %" PRId64 " fee: %" PRId64 " won\n", car, fee);
        total_fee += fee;
        if (fee == 0) {
            free_cars += 1;
        }
        car += 1;
    }
    printf("Total fee: %" PRId64 " won, Free cars: %" PRId64 "\n", total_fee, free_cars);
    return 0;
}

static int64_t parking_fee(int64_t minutes) {
    if (minutes <= 30) return 0;
    int64_t chargeable_minutes = minutes - 30;
    int64_t r = (int64_t)(chargeable_minutes + 9) % 10;
    int64_t q = (int64_t)(chargeable_minutes + 9) / 10;
    int64_t units = (r != 0 && ((int64_t)(chargeable_minutes + 9) < 0) != (10 < 0)) ? q - 1 : q;
    int64_t fee = units * 500;
    if (fee > 5000) {
        fee = 5000;
    }
    return fee;
}
