/* problem2: generated by ppy, C11 */
#include <inttypes.h>
#include <stdint.h>
#include <stdio.h>

static int64_t maximum_parking_time(int64_t budget);
static int64_t parking_fee(int64_t minutes);

int main(void) {
    int64_t budget;

    printf("===Maximum Parking Time===\n");
    printf("Budget (won): ");
    fflush(stdout);
    if (scanf("%" SCNd64, &budget) != 1) { return 1; }
    int64_t maximum_time = maximum_parking_time(budget);
    printf("Maximum parking time: %" PRId64 " minutes\n", maximum_time);
    return 0;
}

static int64_t maximum_parking_time(int64_t budget) {
    int64_t minute = 0;
    int64_t maximum_time = 0;
    while (minute <= 1440) {
        int64_t fee = parking_fee(minute);
        if (fee <= budget) {
            maximum_time = minute;
        }
        minute += 1;
    }
    return maximum_time;
}

static int64_t parking_fee(int64_t minutes) {
    if (minutes <= 30) return 0;
    int64_t chargeable_minutes = minutes - 30;
    int64_t r = (int64_t)(chargeable_minutes + 9) % 10;
    int64_t q = (int64_t)(chargeable_minutes + 9) / 10;
    int64_t units = (r != 0 && ((int64_t)(chargeable_minutes + 9) < 0) != (10 < 0)) ? q - 1 : q;
    int64_t fee = units * 500;
    if (fee > 5000) {
        fee = 5000;
    }
    return fee;
}
