/* problem1: generated by ppy, C++17 */
#include <climits>
#include <cstdio>

static_assert(INT_MAX == 2147483647 && INT_MIN == (-2147483647 - 1),
              "this program requires 32-bit int");

namespace problem1 {
int parking_fee(int minutes) {
    if (minutes <= 30) return 0;
    int chargeable_minutes = minutes - 30;
    int units = (chargeable_minutes + 9) / 10;
    int fee = units * 500;
    if (fee > 5000) {
        fee = 5000;
    }
    return fee;
}

} // namespace problem1

int main() {
    std::printf("===Parking Fee Calculator===\n");
    std::printf("Number of cars: ");
    std::fflush(stdout);
    int number_of_cars;
    if (std::scanf("%d", &number_of_cars) != 1) {
        return 1;
    }
    int total_fee = 0;
    int free_cars = 0;
    int car = 1;
    while (car <= number_of_cars) {
        std::printf("Car %d parking time (minutes): ", car);
        std::fflush(stdout);
        int parking_time;
        if (std::scanf("%d", &parking_time) != 1) {
            return 1;
        }
        int fee = problem1::parking_fee(parking_time);
        std::printf("Car %d fee: %d won\n", car, fee);
        total_fee += fee;
        if (fee == 0) {
            free_cars += 1;
        }
        car += 1;
    }
    std::printf("Total fee: %d won, Free cars: %d\n", total_fee, free_cars);
    return 0;
}
