/* problem2: generated by ppy, C++17 */
#include <cinttypes>
#include <cstdint>
#include <cstdio>

namespace problem2 {
std::int64_t maximum_parking_time(std::int64_t budget);
} // namespace problem2

namespace problem2 {
std::int64_t parking_fee(std::int64_t minutes);
} // namespace problem2


int main() {
    std::int64_t budget;

    std::printf("===Maximum Parking Time===\n");
    std::printf("Budget (won): ");
    std::fflush(stdout);
    if (std::scanf("%" SCNd64, &budget) != 1) { return 1; }
    std::int64_t maximum_time = problem2::maximum_parking_time(budget);
    std::printf("Maximum parking time: %" PRId64 " minutes\n", maximum_time);
    return 0;
}

namespace problem2 {
std::int64_t maximum_parking_time(std::int64_t budget) {
    std::int64_t minute = 0;
    std::int64_t maximum_time = 0;
    while (minute <= 1440) {
        std::int64_t fee = problem2::parking_fee(minute);
        if (fee <= budget) {
            maximum_time = minute;
        }
        minute += 1;
    }
    return maximum_time;
}

} // namespace problem2

namespace problem2 {
std::int64_t parking_fee(std::int64_t minutes) {
    if (minutes <= 30) return 0;
    std::int64_t chargeable_minutes = minutes - 30;
    std::int64_t r = static_cast<std::int64_t>(chargeable_minutes + 9) % 10;
    std::int64_t q = static_cast<std::int64_t>(chargeable_minutes + 9) / 10;
    std::int64_t units = (r != 0 && (static_cast<std::int64_t>(chargeable_minutes + 9) < 0) != (10 < 0)) ? q - 1 : q;
    std::int64_t fee = units * 500;
    if (fee > 5000) {
        fee = 5000;
    }
    return fee;
}

} // namespace problem2
